- hosts: all
  become: true
  tasks:

  - name: download file
    unarchive:
      src: https://raw.githubusercontent.com/crocplays/ansible-demo/main/files/test.zip
      dest: /home/croc
      remote_src: yes
      mode: 0755
      owner: root
      group: root
