---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for adi
    tags: always
    authorized_key:
      user: adi
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBu67DPJiCjUimWIHBQzpW7oSARh3QM0mXrZkGDcdKEx ansible"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache,apache php and git packages
    tags: apache,apache2,git,ubuntu
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ git_package }}"
      state: latest

- hosts: file_servers
  become: true
  tasks:
  - name: install git
    tags: git,ubuntu
    package:
      name:
        - "{{ git_package }}"
      state: latest


