---

- hosts: all
  become: true
  tasks:

  - name: install apache,apache php and git packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ git_package }}"
      state: latest
      update_cache: yes

